---
title: "Exploratory Data Analysis"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE, warning=FALSE, message=FALSE}
library(flexdashboard)
library(tidyverse)
library(visdat)
library(palmerpenguins)
library(DT)
```

# Overview

## Column {data-width="550"}

### 

```{r}
valueBox(dim(penguins)[1], caption="Number of observations",
         icon="fa-pencil")
```

###

```{r}
valueBox(dim(penguins)[2], caption="Number of variables")
```

### Type of data

```{r}
visdat::vis_dat(penguins)
```

## Column {data-width="550"}

# Bi-variate Relationships

```{r}
library(plotly)
p1 <- penguins %>%
  select(species, body_mass_g, ends_with("_mm")) %>%
  GGally::ggpairs(aes(color = species)) +
  scale_colour_manual(values = c("darkorange","purple","cyan4")) +
  scale_fill_manual(values = c("darkorange","purple","cyan4"))
ggplotly(p1)
```

# Deep dive into Bi-variate relations

## Column {data-width="550"}

###

```{r}
g1 <- ggplot(data = penguins, aes(x = flipper_length_mm, y = body_mass_g)) +
  geom_point(aes(color = species,
                 shape = species),
             size = 2) +
  scale_color_manual(values = c("darkorange","darkorchid","cyan4"))
ggplotly(g1)
```

###


```{r, comment=NA, message=FALSE, warning=FALSE}

a1 <- ggplot(penguins, aes(x = bill_length_mm, y = body_mass_g, color=species)) +
   geom_point() + geom_density_2d() +
  scale_color_manual(values = c("darkorange","purple","cyan4")) +
  labs(title = "The scatter plot of body mass index vs bill length",
       subtitle = "Bill length and body mass for Adelie, Chinstrap and Gentoo Penguins",
       x = "Bill length (mm)",
       y = "Body mass (g)",
       color = "Penguin species")
ggplotly(a1)

```


## Column {data-width="550"}

###


```{r, comment=NA, message=FALSE, warning=FALSE}
library(ggridges)
a4 <- ggplot(penguins, aes(x = flipper_length_mm, y = species)) +
  geom_density_ridges(aes(fill = species)) +
  scale_fill_manual(values = c("darkorange","purple","cyan4")) + 
  labs(x = "Flipper length (mm)", title="Distribution of flipper length by species")
a4

```

###

# Data

```{r}
datatable(penguins,
          extensions = 'Buttons',
          options = list(
            dom ='Bfrtip',
            buttons = c('copy',
                        'print',
                        'csv')
          ))
```











